package com.muppetplatform.{{java_package_name}};

import io.micronaut.runtime.Micronaut;

/**
 * Main application class for {{muppet_name}} muppet.
 * Generated by Muppet Platform.
 */
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class, args);
    }
}