package com.muppetplatform.verify_java_micronaut_1766584237;

import io.micronaut.runtime.Micronaut;

/**
 * Main application class for verify-java-micronaut-1766584237 muppet.
 * Generated by Muppet Platform.
 */
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class, args);
    }
}