#!/bin/bash
set -e

# Setup script for real AWS and GitHub integrations
# This script configures the platform to use real services instead of mocks

echo "🚀 Setting up Muppet Platform for Real Integrations"
echo "=================================================="

# Check prerequisites
echo "📋 Checking prerequisites..."

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI is not installed. Please install it first:"
    echo "   https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
    exit 1
fi

# Check if GitHub CLI is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI is not installed. Please install it first:"
    echo "   https://cli.github.com/"
    exit 1
fi

# Check AWS credentials
echo "🔐 Checking AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
    echo "❌ AWS credentials not configured. Please run:"
    echo "   aws configure"
    echo "   or set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables"
    exit 1
fi

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=$(aws configure get region || echo "us-west-2")
echo "✅ AWS Account: $AWS_ACCOUNT_ID"
echo "✅ AWS Region: $AWS_REGION"

# Check GitHub authentication
echo "🔐 Checking GitHub authentication..."
if ! gh auth status &> /dev/null; then
    echo "❌ GitHub CLI not authenticated. Please run:"
    echo "   gh auth login"
    exit 1
fi

GITHUB_USER=$(gh api user --jq .login)
echo "✅ GitHub User: $GITHUB_USER"

# Create real integration environment file
echo "📝 Creating real integration environment configuration..."
cat > .env.real << EOF
# Real Integration Environment Configuration
# Generated by setup-real-integrations.sh

# Mode Configuration
DEBUG=false
LOG_LEVEL=INFO
INTEGRATION_MODE=real

# AWS Configuration
AWS_REGION=$AWS_REGION
AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
AWS_FARGATE_CLUSTER_NAME=muppet-platform-cluster
AWS_VPC_CIDR=10.0.0.0/16
AWS_AVAILABILITY_ZONES=["$AWS_REGION"a","$AWS_REGION"b"]
# AWS credentials should be configured via AWS CLI or environment variables

# GitHub Configuration
GITHUB_TOKEN=\$(gh auth token)
GITHUB_ORGANIZATION=muppet-platform

# Platform Configuration
NAME=platform-service
VERSION=0.1.0
PORT=8000

# Monitoring Configuration
MONITORING_CLOUDWATCH_LOG_RETENTION_DAYS=7
MONITORING_CLOUDWATCH_METRICS_ENABLED=true
MONITORING_CLOUDWATCH_ALARMS_ENABLED=true

# MCP Configuration
MCP_NAME=mcp-server
MCP_PORT=8001
MCP_PROTOCOL=stdio
EOF

echo "✅ Created .env.real configuration file"

# Validate GitHub organization access
echo "🏢 Checking GitHub organization access..."
if gh api orgs/muppet-platform &> /dev/null; then
    echo "✅ Access to muppet-platform organization confirmed"
else
    echo "⚠️  No access to muppet-platform organization"
    echo "   You may need to:"
    echo "   1. Create the organization: https://github.com/organizations/new"
    echo "   2. Or use a different organization name in .env.real"
fi

# Check required AWS permissions
echo "🔒 Checking AWS permissions..."
REQUIRED_PERMISSIONS=(
    "ecs:CreateCluster"
    "ecs:CreateService"
    "ecs:RegisterTaskDefinition"
    "ecr:CreateRepository"
    "ecr:GetAuthorizationToken"
    "logs:CreateLogGroup"
    "ssm:PutParameter"
    "ssm:GetParameter"
    "iam:CreateRole"
    "iam:AttachRolePolicy"
)

echo "   Checking key permissions (this may take a moment)..."
PERMISSION_ERRORS=0

# Test ECS permissions
if ! aws ecs describe-clusters --cluster-names test-permission-check &> /dev/null; then
    if [[ $? -ne 254 ]]; then  # 254 is "cluster not found", which is OK
        echo "   ⚠️  ECS permissions may be limited"
        ((PERMISSION_ERRORS++))
    fi
fi

# Test ECR permissions
if ! aws ecr describe-repositories --max-items 1 &> /dev/null; then
    echo "   ⚠️  ECR permissions may be limited"
    ((PERMISSION_ERRORS++))
fi

if [[ $PERMISSION_ERRORS -eq 0 ]]; then
    echo "✅ AWS permissions look good"
else
    echo "⚠️  Some AWS permissions may be limited. Manual testing may encounter issues."
    echo "   Ensure your AWS user/role has permissions for ECS, ECR, CloudWatch, SSM, and IAM"
fi

# Create manual testing directory structure
echo "📁 Creating manual testing directory structure..."
mkdir -p manual-tests/{scenarios,scripts,docs,cleanup}

# Create basic manual test scenario
cat > manual-tests/scenarios/01-basic-muppet-creation.md << 'EOF'
# Manual Test Scenario 1: Basic Muppet Creation

## Objective
Test end-to-end muppet creation with real AWS and GitHub integrations.

## Prerequisites
- Real integrations configured (run setup-real-integrations.sh)
- AWS credentials configured
- GitHub authentication configured
- Platform service running

## Test Steps

### 1. Start Platform Service
```bash
# Use real integration environment
cp .env.real .env
python -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
```

### 2. Test MCP Tools (using Kiro or direct API)
```bash
# List available templates
curl -X POST http://localhost:8000/mcp/tools/execute \
  -H "Content-Type: application/json" \
  -d '{"tool": "list_templates", "arguments": {}}'

# Create a test muppet
curl -X POST http://localhost:8000/mcp/tools/execute \
  -H "Content-Type: application/json" \
  -d '{"tool": "create_muppet", "arguments": {"name": "test-manual-muppet", "template": "java-micronaut"}}'
```

### 3. Verify GitHub Repository Creation
- Check https://github.com/muppet-platform/test-manual-muppet
- Verify repository has template code
- Check branch protection rules
- Verify GitHub Actions workflows

### 4. Verify AWS Resources
```bash
# Check ECS cluster
aws ecs describe-clusters --clusters muppet-platform-cluster

# Check ECR repository
aws ecr describe-repositories --repository-names test-manual-muppet

# Check Parameter Store
aws ssm get-parameters-by-path --path "/muppet-platform/test-manual-muppet"
```

### 5. Test Muppet Status
```bash
# Get muppet status
curl -X POST http://localhost:8000/mcp/tools/execute \
  -H "Content-Type: application/json" \
  -d '{"tool": "get_muppet_status", "arguments": {"name": "test-manual-muppet"}}'
```

### 6. Cleanup
```bash
# Delete the test muppet
curl -X POST http://localhost:8000/mcp/tools/execute \
  -H "Content-Type: application/json" \
  -d '{"tool": "delete_muppet", "arguments": {"name": "test-manual-muppet"}}'
```

## Expected Results
- ✅ GitHub repository created with template code
- ✅ AWS ECS cluster and ECR repository created
- ✅ Parameter Store entries created
- ✅ Muppet status shows "creating" then "running"
- ✅ Cleanup removes all resources

## Troubleshooting
- Check AWS CloudWatch logs for errors
- Verify GitHub token has organization permissions
- Check AWS permissions for ECS, ECR, SSM access
EOF

echo "✅ Created basic manual test scenario"

# Create cleanup script
cat > manual-tests/cleanup/cleanup-test-resources.sh << 'EOF'
#!/bin/bash
set -e

echo "🧹 Cleaning up manual test resources..."

# Get AWS account info
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=$(aws configure get region || echo "us-west-2")

echo "Cleaning up resources in AWS Account: $AWS_ACCOUNT_ID, Region: $AWS_REGION"

# List of test muppet names to clean up
TEST_MUPPETS=(
    "test-manual-muppet"
    "demo-muppet"
    "integration-test-muppet"
)

for muppet in "${TEST_MUPPETS[@]}"; do
    echo "Cleaning up resources for: $muppet"
    
    # Delete ECS service if exists
    if aws ecs describe-services --cluster muppet-platform-cluster --services "$muppet" &> /dev/null; then
        echo "  Deleting ECS service: $muppet"
        aws ecs update-service --cluster muppet-platform-cluster --service "$muppet" --desired-count 0 || true
        aws ecs delete-service --cluster muppet-platform-cluster --service "$muppet" || true
    fi
    
    # Delete ECR repository if exists
    if aws ecr describe-repositories --repository-names "$muppet" &> /dev/null; then
        echo "  Deleting ECR repository: $muppet"
        aws ecr delete-repository --repository-name "$muppet" --force || true
    fi
    
    # Delete Parameter Store parameters
    echo "  Deleting Parameter Store parameters for: $muppet"
    aws ssm delete-parameters-by-path --path "/muppet-platform/$muppet" --recursive || true
    
    # Delete CloudWatch log group
    echo "  Deleting CloudWatch log group: /aws/fargate/$muppet"
    aws logs delete-log-group --log-group-name "/aws/fargate/$muppet" || true
    
    # Delete GitHub repository (if exists and accessible)
    if gh repo view "muppet-platform/$muppet" &> /dev/null; then
        echo "  Deleting GitHub repository: muppet-platform/$muppet"
        gh repo delete "muppet-platform/$muppet" --confirm || true
    fi
done

# Clean up ECS cluster if empty
echo "Checking if ECS cluster can be cleaned up..."
SERVICES=$(aws ecs list-services --cluster muppet-platform-cluster --query 'serviceArns' --output text)
if [[ -z "$SERVICES" || "$SERVICES" == "None" ]]; then
    echo "  ECS cluster is empty, deleting: muppet-platform-cluster"
    aws ecs delete-cluster --cluster muppet-platform-cluster || true
else
    echo "  ECS cluster still has services, keeping it"
fi

echo "✅ Cleanup complete"
EOF

chmod +x manual-tests/cleanup/cleanup-test-resources.sh
echo "✅ Created cleanup script"

# Create interactive testing script
cat > manual-tests/scripts/interactive-test.py << 'EOF'
#!/usr/bin/env python3
"""
Interactive manual testing script for Muppet Platform.

This script provides an interactive interface for testing platform
functionality with real AWS and GitHub integrations.
"""

import asyncio
import json
import logging
import os
import sys
from typing import Dict, Any

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'src'))

from config import get_settings
from platform_mcp.tools import MCPToolRegistry

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)


class InteractiveTester:
    """Interactive testing interface for manual platform testing."""
    
    def __init__(self):
        self.settings = get_settings()
        self.tool_registry = None
        self.test_muppets = []
    
    async def initialize(self):
        """Initialize the testing environment."""
        logger.info("🚀 Initializing Interactive Muppet Platform Tester")
        logger.info("=" * 50)
        
        # Check if we're in real integration mode
        integration_mode = os.getenv('INTEGRATION_MODE', 'mock')
        logger.info(f"Integration Mode: {integration_mode}")
        
        if integration_mode != 'real':
            logger.warning("⚠️  Not in real integration mode. Set INTEGRATION_MODE=real for full testing.")
        
        # Initialize tool registry
        self.tool_registry = MCPToolRegistry()
        
        # Verify connectivity
        await self._verify_connectivity()
    
    async def _verify_connectivity(self):
        """Verify connectivity to external services."""
        logger.info("🔍 Verifying connectivity...")
        
        # Test GitHub connectivity
        github_token = os.getenv('GITHUB_TOKEN')
        if github_token:
            logger.info("✅ GitHub token configured")
        else:
            logger.warning("⚠️  GitHub token not configured")
        
        # Test AWS connectivity
        aws_region = os.getenv('AWS_REGION', 'us-west-2')
        logger.info(f"✅ AWS region: {aws_region}")
    
    async def run_interactive_session(self):
        """Run the interactive testing session."""
        while True:
            print("\n" + "=" * 50)
            print("🎭 Muppet Platform Interactive Tester")
            print("=" * 50)
            print("1. List available templates")
            print("2. Create a test muppet")
            print("3. Get muppet status")
            print("4. List all muppets")
            print("5. Delete a test muppet")
            print("6. Test pipeline management")
            print("7. Test steering documentation")
            print("8. Run cleanup")
            print("9. Exit")
            print("-" * 50)
            
            choice = input("Select an option (1-9): ").strip()
            
            try:
                if choice == '1':
                    await self._test_list_templates()
                elif choice == '2':
                    await self._test_create_muppet()
                elif choice == '3':
                    await self._test_get_muppet_status()
                elif choice == '4':
                    await self._test_list_muppets()
                elif choice == '5':
                    await self._test_delete_muppet()
                elif choice == '6':
                    await self._test_pipeline_management()
                elif choice == '7':
                    await self._test_steering_docs()
                elif choice == '8':
                    await self._run_cleanup()
                elif choice == '9':
                    break
                else:
                    print("❌ Invalid choice. Please select 1-9.")
            except Exception as e:
                logger.error(f"❌ Test failed: {e}")
                print(f"Error: {e}")
    
    async def _test_list_templates(self):
        """Test listing available templates."""
        print("\n📋 Testing: List Templates")
        result = await self.tool_registry.execute_tool("list_templates", {})
        response = json.loads(result)
        
        if "templates" in response:
            print(f"✅ Found {len(response['templates'])} templates:")
            for template in response['templates']:
                print(f"   - {template['name']}: {template['description']}")
        else:
            print("❌ No templates found or error occurred")
            print(f"Response: {result}")
    
    async def _test_create_muppet(self):
        """Test creating a muppet."""
        print("\n🎭 Testing: Create Muppet")
        
        muppet_name = input("Enter muppet name (or press Enter for 'test-manual-muppet'): ").strip()
        if not muppet_name:
            muppet_name = "test-manual-muppet"
        
        template = input("Enter template name (or press Enter for 'java-micronaut'): ").strip()
        if not template:
            template = "java-micronaut"
        
        print(f"Creating muppet: {muppet_name} with template: {template}")
        
        result = await self.tool_registry.execute_tool("create_muppet", {
            "name": muppet_name,
            "template": template
        })
        
        response = json.loads(result)
        if response.get("success"):
            print(f"✅ Muppet created successfully!")
            print(f"   Repository: {response.get('repository', {}).get('url', 'N/A')}")
            self.test_muppets.append(muppet_name)
        else:
            print(f"❌ Failed to create muppet: {response.get('error', 'Unknown error')}")
    
    async def _test_get_muppet_status(self):
        """Test getting muppet status."""
        print("\n📊 Testing: Get Muppet Status")
        
        if self.test_muppets:
            print("Available test muppets:")
            for i, muppet in enumerate(self.test_muppets, 1):
                print(f"   {i}. {muppet}")
            
            choice = input("Select muppet number or enter custom name: ").strip()
            if choice.isdigit() and 1 <= int(choice) <= len(self.test_muppets):
                muppet_name = self.test_muppets[int(choice) - 1]
            else:
                muppet_name = choice
        else:
            muppet_name = input("Enter muppet name: ").strip()
        
        if not muppet_name:
            print("❌ No muppet name provided")
            return
        
        result = await self.tool_registry.execute_tool("get_muppet_status", {
            "name": muppet_name
        })
        
        response = json.loads(result)
        if response.get("success", True):  # Some tools don't return success field
            print(f"✅ Status for {muppet_name}:")
            if "muppet" in response:
                muppet_info = response["muppet"]
                print(f"   Status: {muppet_info.get('status', 'unknown')}")
                print(f"   Template: {muppet_info.get('template', 'unknown')}")
                print(f"   GitHub: {muppet_info.get('github_repo', 'N/A')}")
        else:
            print(f"❌ Failed to get status: {response.get('error', 'Unknown error')}")
    
    async def _test_list_muppets(self):
        """Test listing all muppets."""
        print("\n📝 Testing: List Muppets")
        
        result = await self.tool_registry.execute_tool("list_muppets", {})
        response = json.loads(result)
        
        if "muppets" in response:
            muppets = response["muppets"]
            print(f"✅ Found {len(muppets)} muppets:")
            for muppet in muppets:
                print(f"   - {muppet.get('name', 'unknown')} ({muppet.get('status', 'unknown')})")
        else:
            print("❌ No muppets found or error occurred")
            print(f"Response: {result}")
    
    async def _test_delete_muppet(self):
        """Test deleting a muppet."""
        print("\n🗑️  Testing: Delete Muppet")
        
        if self.test_muppets:
            print("Available test muppets:")
            for i, muppet in enumerate(self.test_muppets, 1):
                print(f"   {i}. {muppet}")
            
            choice = input("Select muppet number to delete or enter custom name: ").strip()
            if choice.isdigit() and 1 <= int(choice) <= len(self.test_muppets):
                muppet_name = self.test_muppets[int(choice) - 1]
            else:
                muppet_name = choice
        else:
            muppet_name = input("Enter muppet name to delete: ").strip()
        
        if not muppet_name:
            print("❌ No muppet name provided")
            return
        
        confirm = input(f"⚠️  Are you sure you want to delete '{muppet_name}'? (yes/no): ").strip().lower()
        if confirm != 'yes':
            print("❌ Deletion cancelled")
            return
        
        result = await self.tool_registry.execute_tool("delete_muppet", {
            "name": muppet_name
        })
        
        response = json.loads(result)
        if response.get("success"):
            print(f"✅ Muppet '{muppet_name}' deleted successfully!")
            if muppet_name in self.test_muppets:
                self.test_muppets.remove(muppet_name)
        else:
            print(f"❌ Failed to delete muppet: {response.get('error', 'Unknown error')}")
    
    async def _test_pipeline_management(self):
        """Test pipeline management tools."""
        print("\n🔧 Testing: Pipeline Management")
        print("1. List workflow versions")
        print("2. Update muppet pipelines")
        print("3. Rollback muppet pipelines")
        
        choice = input("Select pipeline test (1-3): ").strip()
        
        if choice == '1':
            template_type = input("Enter template type (or press Enter for 'java-micronaut'): ").strip()
            if not template_type:
                template_type = "java-micronaut"
            
            result = await self.tool_registry.execute_tool("list_workflow_versions", {
                "template_type": template_type
            })
            response = json.loads(result)
            print(f"Workflow versions for {template_type}:")
            print(json.dumps(response, indent=2))
        
        elif choice in ['2', '3']:
            muppet_name = input("Enter muppet name: ").strip()
            workflow_version = input("Enter workflow version (e.g., 'java-micronaut-v1.2.3'): ").strip()
            
            if not muppet_name or not workflow_version:
                print("❌ Both muppet name and workflow version are required")
                return
            
            tool_name = "update_muppet_pipelines" if choice == '2' else "rollback_muppet_pipelines"
            result = await self.tool_registry.execute_tool(tool_name, {
                "muppet_name": muppet_name,
                "workflow_version": workflow_version
            })
            
            response = json.loads(result)
            if response.get("success"):
                action = "updated" if choice == '2' else "rolled back"
                print(f"✅ Pipelines {action} successfully!")
            else:
                print(f"❌ Pipeline operation failed: {response.get('error', 'Unknown error')}")
    
    async def _test_steering_docs(self):
        """Test steering documentation tools."""
        print("\n📚 Testing: Steering Documentation")
        print("1. List steering docs")
        print("2. Update shared steering")
        
        choice = input("Select steering test (1-2): ").strip()
        
        if choice == '1':
            muppet_name = input("Enter muppet name (optional): ").strip()
            args = {"muppet_name": muppet_name} if muppet_name else {}
            
            result = await self.tool_registry.execute_tool("list_steering_docs", args)
            response = json.loads(result)
            print("Steering documentation:")
            print(json.dumps(response, indent=2))
        
        elif choice == '2':
            result = await self.tool_registry.execute_tool("update_shared_steering", {})
            response = json.loads(result)
            if response.get("success"):
                print("✅ Shared steering updated successfully!")
            else:
                print(f"❌ Steering update failed: {response.get('error', 'Unknown error')}")
    
    async def _run_cleanup(self):
        """Run cleanup of test resources."""
        print("\n🧹 Running Cleanup")
        
        if self.test_muppets:
            print("Test muppets to clean up:")
            for muppet in self.test_muppets:
                print(f"   - {muppet}")
            
            confirm = input("Delete all test muppets? (yes/no): ").strip().lower()
            if confirm == 'yes':
                for muppet in self.test_muppets[:]:  # Copy list to avoid modification during iteration
                    try:
                        result = await self.tool_registry.execute_tool("delete_muppet", {
                            "name": muppet
                        })
                        response = json.loads(result)
                        if response.get("success"):
                            print(f"✅ Deleted {muppet}")
                            self.test_muppets.remove(muppet)
                        else:
                            print(f"❌ Failed to delete {muppet}: {response.get('error')}")
                    except Exception as e:
                        print(f"❌ Error deleting {muppet}: {e}")
        else:
            print("No test muppets to clean up")
    
    async def cleanup(self):
        """Cleanup resources."""
        if self.tool_registry:
            # Any cleanup needed for tool registry
            pass


async def main():
    """Main function for interactive testing."""
    tester = InteractiveTester()
    
    try:
        await tester.initialize()
        await tester.run_interactive_session()
    except KeyboardInterrupt:
        print("\n👋 Testing session interrupted by user")
    except Exception as e:
        logger.error(f"❌ Testing session failed: {e}")
        return 1
    finally:
        await tester.cleanup()
    
    print("👋 Testing session complete")
    return 0


if __name__ == "__main__":
    exit(asyncio.run(main()))
EOF

chmod +x manual-tests/scripts/interactive-test.py
echo "✅ Created interactive testing script"

# Create documentation
cat > manual-tests/docs/README.md << 'EOF'
# Manual Testing with Real Integrations

This directory contains tools and documentation for manually testing the Muppet Platform with real AWS and GitHub integrations.

## Quick Start

1. **Setup Real Integrations**
   ```bash
   ./scripts/setup-real-integrations.sh
   ```

2. **Start Platform with Real Integrations**
   ```bash
   cp .env.real .env
   python -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
   ```

3. **Run Interactive Tests**
   ```bash
   cd manual-tests
   python scripts/interactive-test.py
   ```

4. **Cleanup Test Resources**
   ```bash
   ./manual-tests/cleanup/cleanup-test-resources.sh
   ```

## Directory Structure

- `scenarios/` - Step-by-step manual test scenarios
- `scripts/` - Interactive testing scripts and utilities
- `docs/` - Testing documentation and guides
- `cleanup/` - Resource cleanup scripts

## Prerequisites

- AWS CLI configured with appropriate permissions
- GitHub CLI authenticated
- Python environment with platform dependencies
- Access to muppet-platform GitHub organization

## Test Scenarios

1. **Basic Muppet Creation** (`scenarios/01-basic-muppet-creation.md`)
   - End-to-end muppet creation with real services
   - GitHub repository creation and configuration
   - AWS resource provisioning

2. **Pipeline Management** (Coming soon)
   - Workflow version management
   - Pipeline updates and rollbacks

3. **Steering Documentation** (Coming soon)
   - Document distribution and updates
   - Cross-muppet synchronization

## Troubleshooting

### Common Issues

1. **AWS Permission Errors**
   - Ensure your AWS user/role has ECS, ECR, CloudWatch, SSM, and IAM permissions
   - Check AWS CLI configuration: `aws sts get-caller-identity`

2. **GitHub Authentication Issues**
   - Verify GitHub CLI authentication: `gh auth status`
   - Check organization access: `gh api orgs/muppet-platform`

3. **Platform Service Errors**
   - Check logs in `logs/platform.log`
   - Verify environment configuration in `.env`

### Getting Help

- Check CloudWatch logs for AWS-related errors
- Review GitHub API rate limits and permissions
- Verify network connectivity to AWS and GitHub services
EOF

echo "✅ Created manual testing documentation"

echo ""
echo "🎉 Real Integration Setup Complete!"
echo "=================================="
echo ""
echo "Next Steps:"
echo "1. Review the configuration in .env.real"
echo "2. Start the platform with real integrations:"
echo "   cp .env.real .env"
echo "   python -m uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "3. Run interactive tests:"
echo "   cd manual-tests"
echo "   python scripts/interactive-test.py"
echo ""
echo "4. Follow test scenarios in manual-tests/scenarios/"
echo ""
echo "5. Clean up test resources when done:"
echo "   ./manual-tests/cleanup/cleanup-test-resources.sh"
echo ""
echo "📚 Documentation: manual-tests/docs/README.md"